# site settings

title: Joseph Gordon
description: Senior Recruiting Partner
taglong: Online visaul CV
tagshort: Visaul CV
url: https://recruiter-joe.github.io
baseurl: ""
permalink: pretty
repo: https://Recruiter-Joe/recruiter-joe.github.io

# author settings

author:
  name: Place Holder
  email: jgordon.career@gmail.com
photo: /assets/photo.jpg

# build settings

exclude:
  - LICENSE
  - README.md

sass:
  sass_dir: _sass
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
